---
swagger: "2.0"

################################################################################
#                              API Information                                 #
################################################################################
info:
  version: "1.0.0"
  title: "asterisk-ws reactor"
  description: |
    - Это Backend проекта [asterisk-ws-react](https://github.com/ars-anosov/asterisk-ws-react)
    - Транслирует AMI events Asterisk по WebSocket в React компоненты
    
    Тест WebSocket - [ws_test](/ws_test)
    Готовый Frontend - [front_build](/front_build)

################################################################################
#                  Host, Base Path, Schemes and Content Types                  #
################################################################################
host: '192.168.13.97:8018'
basePath: /v2api
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json

################################################################################
#                                   Tags                                       #
################################################################################
tags:
  - name: Client
    description: Авторизация в админке

################################################################################
#                                    Paths                                     #
################################################################################
paths:

  /client/token:
    get:
      tags:
        - Client
      summary: Получить временный token авторизации
      description: Получаем token
      operationId: token_get
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: auth_name
          in: query
          required: true
          type: string
          description: Имя пользователя
        - name: auth_pass
          in: query
          required: true
          type: string
          description: Пароль
      responses:
        200:
          description: token
          schema:
            $ref: '#/definitions/client_token_get'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
      x-swagger-router-controller: Client
    x-swagger-router-controller: Client

################################################################################
#                                 Definitions                                  #
################################################################################
definitions:

# client_token_get ------------------------------------------------------------
  client_token_get:
    type: "object"
    properties:
      token:
        type: "string"
      fio:
        type: "string"


# system ----------------------------------------------------------------------
  dummy:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"

  errorModel:
    type: "object"
    required:
    - "code"
    - "message"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
