export const AUTH_TOKEN_DISPLAY_BLK   = 'AUTH_TOKEN_DISPLAY_BLK'
export const AUTH_TOKEN_GET_REQUEST   = 'AUTH_TOKEN_GET_REQUEST'
export const AUTH_TOKEN_GET_SUCCESS   = 'AUTH_TOKEN_GET_SUCCESS'
export const AUTH_TOKEN_GET_202       = 'AUTH_TOKEN_GET_202'

export const AUTH_DATA_USER_INPUT     = 'AUTH_DATA_USER_INPUT'