export const WSCTL_DISPLAY_BLK      = 'WSCTL_DISPLAY_BLK'

export const WSCTL_CONNECT_REQUEST  = 'WSCTL_CONNECT_REQUEST'
export const WSCTL_CONNECT_SUCCESS  = 'WSCTL_CONNECT_SUCCESS'
export const WSCTL_DISCONNECT_OK    = 'WSCTL_DISCONNECT_OK'
export const WSCTL_DISCONNECT_ERR   = 'WSCTL_DISCONNECT_ERR'

export const WS_MSG_EVENT           = 'WS_MSG_EVENT'